"""Deflated Sharpe Ratio research implementation.

Implements the Bailey/Lopez de Prado probabilistic Sharpe-ratio correction
for non-normal returns and multiple strategy trials. Research-only.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
import statistics
from typing import Sequence


@dataclass(frozen=True)
class DSRResult:
    observed_sharpe: float
    sample_size: int
    skewness: float
    kurtosis: float
    trial_count: int
    expected_max_sharpe: float
    probabilistic_sharpe: float
    deflated_sharpe_probability: float


_EULER_GAMMA = 0.5772156649015329


def deflated_sharpe_ratio(
    returns: Sequence[float],
    *,
    trial_count: int,
    benchmark_sharpe: float = 0.0,
) -> DSRResult:
    """Calculate the Deflated Sharpe Ratio probability.

    The observed Sharpe is unannualized: mean(return) / sample stdev(return).
    The DSR probability is the probabilistic Sharpe ratio evaluated against
    the expected maximum Sharpe generated by the stated trial universe.

    Parameters
    ----------
    returns:
        Independent strategy/trade-period returns used consistently for the
        observed Sharpe estimate.
    trial_count:
        Complete number of strategy trials in the selection universe. This is
        explicit by design; callers must not infer it from an unrelated list.
    benchmark_sharpe:
        Null/benchmark Sharpe. Defaults to zero.
    """
    values = _validate_returns(returns)
    n = len(values)
    if n < 2:
        raise ValueError("at least 2 returns are required")
    if not isinstance(trial_count, int) or isinstance(trial_count, bool) or trial_count < 1:
        raise ValueError("trial_count must be a positive integer")
    if not math.isfinite(float(benchmark_sharpe)):
        raise ValueError("benchmark_sharpe must be finite")

    mean = statistics.mean(values)
    stdev = statistics.stdev(values)
    if stdev == 0.0:
        observed = math.inf if mean > 0 else (-math.inf if mean < 0 else 0.0)
    else:
        observed = mean / stdev

    skew = _sample_skewness(values)
    kurtosis = _sample_kurtosis(values)
    expected_max = _expected_maximum_sharpe(trial_count)
    threshold = max(float(benchmark_sharpe), expected_max)

    if not math.isfinite(observed):
        psr = 1.0 if observed > threshold else 0.0
    else:
        denominator = math.sqrt(
            1.0 - skew * observed + ((kurtosis - 1.0) / 4.0) * observed * observed
        )
        if denominator <= 0.0 or not math.isfinite(denominator):
            raise ValueError("invalid DSR denominator")
        z = (observed - threshold) * math.sqrt(n - 1.0) / denominator
        psr = statistics.NormalDist().cdf(z)

    return DSRResult(
        observed_sharpe=float(observed),
        sample_size=n,
        skewness=float(skew),
        kurtosis=float(kurtosis),
        trial_count=trial_count,
        expected_max_sharpe=float(expected_max),
        probabilistic_sharpe=float(psr),
        deflated_sharpe_probability=float(psr),
    )


def _expected_maximum_sharpe(trial_count: int) -> float:
    if trial_count == 1:
        return 0.0
    normal = statistics.NormalDist()
    q1 = normal.inv_cdf(1.0 - 1.0 / trial_count)
    q2 = normal.inv_cdf(1.0 - 1.0 / (trial_count * math.e))
    return (1.0 - _EULER_GAMMA) * q1 + _EULER_GAMMA * q2


def _sample_skewness(values: Sequence[float]) -> float:
    n = len(values)
    if n < 3:
        raise ValueError("at least 3 returns are required for skewness")
    mean = statistics.mean(values)
    m2 = sum((x - mean) ** 2 for x in values) / n
    m3 = sum((x - mean) ** 3 for x in values) / n
    if m2 == 0.0:
        return 0.0
    return math.sqrt(n * (n - 1.0)) / (n - 2.0) * m3 / (m2 ** 1.5)


def _sample_kurtosis(values: Sequence[float]) -> float:
    n = len(values)
    if n < 4:
        raise ValueError("at least 4 returns are required for kurtosis")
    mean = statistics.mean(values)
    m2 = sum((x - mean) ** 2 for x in values) / n
    m4 = sum((x - mean) ** 4 for x in values) / n
    if m2 == 0.0:
        return 3.0
    g2 = m4 / (m2 * m2) - 3.0
    return ((n - 1.0) / ((n - 2.0) * (n - 3.0))) * ((n + 1.0) * g2 + 6.0) + 3.0


def _validate_returns(returns: Sequence[float]) -> list[float]:
    values = []
    for i, value in enumerate(returns):
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ValueError(f"return at index {i} must be numeric")
        value = float(value)
        if not math.isfinite(value):
            raise ValueError(f"return at index {i} must be finite")
        values.append(value)
    if len(values) < 2:
        raise ValueError("at least 2 returns are required")
    return values
